baseURL = "/"
languageCode = "en-us"
title = "Monica Norris Portfolio"

timeout = 60000

[menu]
[[menu.main]]
  title = 'Resume'
  name = 'Resume'
  weight = 4
  url = "/uploads/MonicaNorris_Resume.pdf"

[[menu.main]]
  title = 'Contact'
  name = 'Contact'
  weight = 5
  url = "#contact"


[params]
favicon = "images/favicon.png"

images = ["images/favicon.png"]

description = "It is my passion to connect life to designs for all web projects. As an experienced Web Developer, there is a consistent foundation of beauty and ease to every detail within my work."

gtm = "GTM-WW6FZD4"

custom_js = ["js/isotope.js", "js/main.js"]
external_js = ["https://code.jquery.com/jquery-3.6.0.slim.min.js", "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"]