baseURL = "https://mnorris1215.github.io/"
languageCode = "en-us"
title = "Monica Norris Portfolio"

[menu]
[[menu.main]]
  title = 'Resume'
  name = 'Resume'
  weight = 4
  url = "/uploads/monica_norris_resume_2022.pdf"

[[menu.main]]
  title = 'Contact'
  name = 'Contact'
  weight = 5
  url = "#contact"


[params]
custom_js = ["js/isotope.js", "js/main.js"]
external_js = ["https://code.jquery.com/jquery-3.6.0.slim.min.js"]