baseURL = "/"
languageCode = "en-us"
title = "Monica Norris Portfolio"

[menu]
[[menu.main]]
  title = 'Resume'
  name = 'Resume'
  weight = 4
  url = "/uploads/MonicaNorris_Resume.pdf"

[[menu.main]]
  title = 'Contact'
  name = 'Contact'
  weight = 5
  url = "#contact"


[params]
custom_js = ["js/isotope.js", "js/main.js"]
external_js = ["https://code.jquery.com/jquery-3.6.0.slim.min.js", "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"]