[build]
publish = "public"
command = "hugo"

[context.production]
command = "hugo --gc --minify"
publish = "public"

[context.production.processing]
skip_processing = false

[context.production.css]
  bundle = true
  minify = false
[context.production.processing.js]
  bundle = true
  minify = false
[context.production.processing.images]
  compress = true

  [context.production.environment]
    HUGO_VERSION = "0.88.1"
    HUGO_ENV = "production"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"
  publish = "public"

  [context.branch-deploy.environment]
    HUGO_VERSION = "0.88.1"
    HUGO_ENV = "staging"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
